version: "3"
services:
    db:
        container_name: clinicwave-notification-postgres
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: clinicwave-notification
            POSTGRES_USER: ${DOCKER_POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5433:5432"